### ISSUE TITLE
Code review of existing code

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#1]
I should acquaint myself with all the current code that @HuStmpHrrr has written.

- [x] Category.Core
- [x] Category.SubCategory
- [x] Category
- [x] Category.Discrete
- [x] Square.Core
- [x] Morphism
- [x] Category.Groupoid
- [x] Square.Iso
- [x] Square
- [x] Functor.Core
- [x] Functor
- [x] Category.Slice
- [x] Object.Product.Core
- [x] Object.Product.Morphisms
- [x] Diagram.Equalizer
- [x] Category.Morphisms
- [x] Morphism.Properties
- [x] Morphism.Isomorphism
- [x] Functor.Properties
- [x] Object.Product
- [x] Object.Terminal
- [x] Object.Initial
- [x] Object.BinaryProducts
- [x] Diagram.Cone
- [x] Diagram.Limit
- [x] Diagram.Pullback
- [x] Object.Coproduct
- [x] Object.Exponential
- [x] NaturalTransformation.Core
- [x] NaturalTransformation
- [x] NaturalTransformation.NaturalIsomorphism
- [x] Monad
- [x] Category.Cats
- [x] Category.Product
- [x] Functor.Bifunctor
- [x] Category.Sets
- [x] Functor.Hom
- [x] Category.Functors
- [x] Category.Monoidal
- [x] Category.Monoidal.Properties
- [x] Functor.Power
- [x] Adjoint

**Comment by HuStmpHrrr** [comment]
I did not apply too much creativity and just try to port whatever originally there to here using more 2.6-ish style. I probably altered some notations and proofs. also do you think there are some problems in the previous library that you don't want to replicate in this library?

**Comment by JacquesCarette** [comment]
One of the problems is that the old library created (duplicated?) a lot of functionality that should have been in the standard library, instead of re-using it. In particular for doing various kinds of equational reasoning.

There was also some use of Heterogeneous equality that I didn't think was needed.

And the whole library should be fine to be used `--without-K` (and now, `--safe`). At least, most of it, unless it can be explained otherwise.

**Comment by JacquesCarette** [comment]
Ok, I have now caught up.  I can start porting some of the things I need too (and closing some issues that came up with doing the review).
