### ISSUE TITLE
remove `levelOf` from `Category.Core`

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#10]
remove

```agda
 levelOf : ∀ {o ℓ e} → Category o ℓ e → Level 
```

this function should go to stdlib.

**Comment by HuStmpHrrr** [comment]
c.f. agda/agda-stdlib#829

**Comment by HuStmpHrrr** [comment]
https://github.com/agda/agda-categories/commit/f40c00953870f28a8de046b9286472de385bc266

**Comment by JacquesCarette** [comment]
So the "problem" with this, is that `agda-categories` used to work fine on top of v1.0 and above the stdlib -- now it requires the master branch of post-v1.1.  While I'm fine with dropping v1.0, requiring an unreleased library just for `levelOfTerm` seems like asking a lot.

**Comment by HuStmpHrrr** [comment]
hmm... i thought about that too. my thought was that since this library is not close to stable so following stdlib closer seems to speed up iteration. also I find `levelOfTerm` is quite useful because it becomes immediate what level the concept is in.

**Comment by JacquesCarette** [comment]
I guess we really (really!) don't want anything resembling an `#ifdef` anywhere in there, so we have to choose. And relying on a future v1.2 is probably ok. But we should not move further ahead than that!

**Comment by HuStmpHrrr** [comment]
ok fine. I hope it's the last new bit we need from the stdlib.

**Comment by JacquesCarette** [comment]
Or that we can sneak in whatever we need in time for 1.2.
