### ISSUE TITLE
`EnrichedFunctors` should be in `Categories.Enriched.Construction`

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#102]
https://github.com/agda/agda-categories/blob/master/Categories/Category/Construction/EnrichedFunctors.agda

it looks strange for this construction to live with ordinary categories.

**Comment by JacquesCarette** [comment]
I don't think so: https://github.com/agda/agda-categories/blob/afe50323d35e8eaf664ba8c38e781dbd6f941cb6/Categories/Category/Construction/EnrichedFunctors.agda#L26-L27
it builds a `Setoid-Category`.

**Comment by HuStmpHrrr** [comment]
yeah that's right. I am not thinking today.
