### ISSUE TITLE
Shouldn't _≅_ be in Object?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#12]
Right now, it is defined in Morphism, but it is really about two objects being isomorphic. Defining Epi and Mono in Morphism makes sense.

**Comment by HuStmpHrrr** [comment]
because it is really *isormophism*. the `Iso` predicate is really a bad name because that doesn't define isomorphism, but just mutual inverse relation between two morphisms.

**Comment by JacquesCarette** [comment]
It really is *isomorphism* of objects, I agree. It still feels like a construction over objects, as opposed to a property of morphisms...

but stdlib calls this `Equivalence` (between Setoids). It is in `Function.Equivalence`. Which actually goes some ways to convincing me that it does belong in Morphism. But you're right that `Iso` is not a good name.  `Equiv`? Something else?

**Comment by HuStmpHrrr** [comment]
`Equiv f g` sounds like `f` and `g` are equivalent but it is not the case. probably `Inverse`?

I think it has something to do with how people think when perceiving `Iso f g`. people are thinking `f` and `g` together form an isomorphism, which is represented by `A ≅ B` containing both morphisms.

**Comment by JacquesCarette** [comment]
`_≅_` is `Inverse`. stdlib uses `InverseOf` (which in our case would be indexed by 2 objects) for the current `Iso`. I'd be happy with that.

**Comment by HuStmpHrrr** [comment]
`InverseOf` indeed looks better.

**Comment by JacquesCarette** [comment]
After using this in other code, I've decided I'm actually fine with the name. Still not sure of the location, but it doesn't seem too bad, so let's call this moot.
