### ISSUE TITLE
Ordering problem in 2.6.1

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#123]
(@nad reports - see comment https://github.com/agda/agda/issues/4316#issuecomment-589976621)

With version 1.2 of the standard library and Agda 2.6.1-556be02 I get the following error:

    […]/Categories/Category/Instance/Properties/Posets.agda:252,54-55
    Poset a a a !=< _C_1608 ⇒ _A_1603
    when checking that the expression f has type _C_1608 ⇒ _A_1603

My guess is that this problem was caused by a fix of an ordering bug in the generalisation machinery (https://github.com/agda/agda/issues/3779). When I use generalisable variables I bind implicit arguments by name, to avoid surprises if the order of the arguments is changed (primarily due to changes in the program, not changes in Agda).

**Comment by gallais** [comment]
This was my fix for this very problem:

https://github.com/gallais/agda-categories/pull/1/commits/946ab84381e1c7b639137efa624d909651695169#diff-e0d3af684f34ef68eabbe213274f7329L252-R253

Cf. agda/agda#4481 for why I had to use a pattern-matching lambda.

**Comment by JacquesCarette** [comment]
When I had to fix similar problems, I tended to remove the generalizable variables (for the minimal number of definitions) and replace them with a specific order. More future-proof that way, as it didn't seem that the underlying Agda problems were going to be fixed soon.

**Comment by HuStmpHrrr** [comment]
is this issue occurring for 2.6.0.1?

here is what I got:

```agda
/home/hu/projects/agda-categories/src/Categories/Category/Instance/Properties/Posets.agda:252,24-253,53
Unexpected implicit argument
when checking that the clause
.extendedlambda0 {h = h} {f = f} {g = g}
  = ⟨,⟩-unique {f = f} {g = g} {h = h}
has type
{h.A f.B : Category.Obj (Posets a a a)}
{f : (Posets a a a Category.⇒ h.A) f.B}
{g.B : Category.Obj (Posets a a a)}
{h : (Posets a a a Category.⇒ h.A) (f.B × g.B)}
{g : (Posets a a a Category.⇒ h.A) g.B} →
(Posets a a a Category.≈ (Posets a a a Category.∘ π₁) h) f →
(Posets a a a Category.≈ (Posets a a a Category.∘ π₂) h) g →
(Posets a a a Category.≈ ⟨ f , g ⟩) h
```

**Comment by HuStmpHrrr** [comment]
I see. so that fix causes this issue in 2.6.0.1. are we moving on to 2.6.1? but this is not officially released, no? why should this piece come in to master now?

**Comment by HuStmpHrrr** [comment]
I see, so travis uses master branch of agda, doesn' it? I suppose we should use the latest official release, so that we won't be caught by agda's whatever latest bugs. let me start a new issue.

**Comment by HuStmpHrrr** [comment]
I am reverting this change. though my opinion is that agda shouldn't change the way the library is implemented in, i think that's probably too ideal. I propose we should have a dev branch in case we have to touch the code for future agda releases.

**Comment by gallais** [comment]
Btw Agda 2.6.1 is about to be released. Cf. https://github.com/agda/agda/issues/4324#issuecomment-595213618

**Comment by HuStmpHrrr** [comment]
ok i see. sorry I lost in the full picture. let me revert my change.

**Comment by JacquesCarette** [comment]
Should it be a 'dev' branch or an 'experimental' branch?  I believe the latter name is what stdlib uses.
