### ISSUE TITLE
Move TransitiveClosure out of Morphism?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#13]
It isn't used all that often, and so probably belongs on its own.

**Comment by HuStmpHrrr** [comment]
yeah that would do. it's used for meta-purposes.

**Comment by JacquesCarette** [comment]
Where to?

**Comment by HuStmpHrrr** [comment]
probably just `Morphism.TransitiveClosure`?

**Comment by JacquesCarette** [comment]
I was thinking `Category.Construction.TransitiveClosure` (or `Category.Construction.PathCategory`).

**Comment by HuStmpHrrr** [comment]
yeah I think it is better to put in `Category`.
