### ISSUE TITLE
lack of index.html and css

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#130]
it seems the doc has no index.html so it displays 404 and there is no css style so it looks plain,
e.g.
https://agda.github.io/agda-categories/Algebra.html

**Comment by HuStmpHrrr** [comment]
I think this can be fixed by just changing the makefile

**Comment by gallais** [comment]
I don't think the index should be Everything.html: that's a pretty brutal list
of things. It would make sense to have a file giving the central ideas the library
is built around and pointing at key definitions.

Then you can link to Everything.agda

As for the css, it should be as simple as:

```diff
-   - git add -f \*.html
+   - git add -f \*.html \*.css
```

**Comment by HuStmpHrrr** [comment]
that is true.

I will think about what can be a good `index.html`.

**Comment by JacquesCarette** [comment]
I've done the css thing above (will push soon).  We could start with an `index.html` based on the the stdlib does [I was looking at that now, but I'll move on to other things].

**Comment by JacquesCarette** [comment]
Note that the 404 and the CSS bits are done.  But it links to Everything, which is still brutal. So that part still needs done.

**Comment by JacquesCarette** [comment]
The main parts of this are done - I'll open a new issue for a proper ToC.
