### ISSUE TITLE
use 2.6.0.1 in travis

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#131]
we shouldn't use master branch of agda in travis. instead, we should use the latest release. that means we will have to update the version every release but hopefully it's fine.

ideally, it should be agda's continuous integration to compile this library to make sure they don't break anything.

**Comment by HuStmpHrrr** [comment]
c.f. #123

**Comment by HuStmpHrrr** [comment]
https://github.com/agda/agda-categories/commit/294091f6c5b3e5668cafeaa89187add95f0d72a7

**Comment by gallais** [comment]
Broke the build.

I ended up using master precisely because travis did not have enough memory to
compile agda-categories unless we were using the newer version of Agda using
compact regions.
