### ISSUE TITLE
revise categories with families and family of sets

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#139]
I am checking out categorical semantics of type theories recently and got bumped into this concept of categories with families as a framework to model dependent type theories.

I think there is one immediate limitation of the notion implemented currently. the current implementation relies on a functor to family of sets, where sets are identified by propositional equality. however, in actual type theories, we have beta and eta equivalences, which are natural to define as equivalence relation. I think it might be worth reworking family of sets, so that sets are identified up to equivalence, resulting, again, setoids.

**Comment by JacquesCarette** [comment]
Absolutely - it was an early error of mine to base this on raw `Set`. Only later understanding made it clear that it should be on `Setoid`.  Thankfully, the early paper of Dybjer where CwF was defined, he worked out the Setoid case too.  I've even got code somewhere for most of it, but it has likely bit-rotted.

**Comment by JacquesCarette** [comment]
The following two papers references might be quite helpful here:
- [Categories with Families: Unityped, Simply Typed, and Dependently Typed](https://arxiv.org/abs/1904.00827)
- Section 1.1 of [Presheaf Models of Relational Modalities in Dependent Type Theory](https://arxiv.org/abs/1805.08684)

**Comment by JacquesCarette** [comment]
So I might have managed CwF in the Setoid case (in a branch), just. I tried to do Pi types, and that didn't work - the needed transports are beyond me. I'm kind of thinking of taking CwF out of the library completely. I think the 'right' way to do these will follow a different route. There's a bunch of different things out there that are related, maybe one of them would fit better.

Opinions?

**Comment by HuStmpHrrr** [comment]
sure that sounds about right. CwFs are fundamentally set theoretic, so a type theoretic framework won't go through smoothly (though I think it will still be possible and probably easier in a cubical setting).
