### ISSUE TITLE
Submit relation between Fin and _⊎_ to stdlib

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#14]
This is present in both Object.Power and in pi-dual. Should be in neither!

**Comment by JacquesCarette** [comment]
`Object.Power` no longer exists. But this is still in `Functor.Power`.

`unpack` is `Data.Fin.splitAt`.  The opposite function is apparently still not in `Data.Fin` !

**Comment by MatthewDaggitt** [comment]
We actually have it twice!

https://github.com/agda/agda-stdlib/blob/f9a53e8699259c8567d374a31c2c5636efaf50d0/src/Data/Fin/Base.agda#L209

https://github.com/agda/agda-stdlib/blob/f9a53e8699259c8567d374a31c2c5636efaf50d0/src/Data/Fin/Permutation/Components.agda#L40

**Comment by JacquesCarette** [comment]
Two things @MatthewDaggitt : 
1. probably there should an issue filed to remove that duplication?
2. what I meant was the inverse function to `splitAt`, defined inline in https://github.com/agda/agda-stdlib/blob/f9a53e8699259c8567d374a31c2c5636efaf50d0/src/Data/Fin/Properties.agda#L484-L502 in the "proof" that `Fin (m + n) ≃ Fin m ⊎ Fin n` (but which doesn't exist itself anywhere).  i.e.
```agda
unsplit :: {m n : ℕ} (i : ℕ) → Fin m ⊎ Fin n → Fin (m + n)
unsplit = [ inject+ n , raise {n} m ]
```
I'd be happy to call it `join` or `pack` or a whole host of nicer names than `unsplit`.

**Comment by JacquesCarette** [comment]
Is now https://github.com/agda/agda-stdlib/pull/1393.

**Comment by MatthewDaggitt** [comment]
Ah sorry, I was reading too quick and thought you'd written the `opposite` function.

Filed https://github.com/agda/agda-stdlib/issues/1395 for 1.

**Comment by JacquesCarette** [comment]
This has been done, and the uses in the library of the specialized code removed.
