### ISSUE TITLE
Turn on `--no-subtyping` ?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#144]
See issue https://github.com/agda/agda/issues/4474 and PR https://github.com/agda/agda/pull/4475.  I don't think we use subtyping in agda-categories at all (and we shouldn't need to).  I'm also not sure if it would make any 'real' difference (such as in typechecking speed), but it's worth investigating.

**Comment by HuStmpHrrr** [comment]
I am out of context; what subtyping agda has besides the experimental cumulative universes (which I think probably we should turn it on once it's no longer experimental)?

**Comment by gallais** [comment]
* `A` to `.A` (irrelevance)
* `Size< j` to `Size`

**Comment by JacquesCarette** [comment]
Neither of which is used (i.e. irrelevance or sized types).  So we should be able to use it -- and it should make no effective difference.  In theory.

**Comment by JacquesCarette** [comment]
So it appears that subtyping was turned off by default in 2.6.1, and nothing broke.  Not sure if forcing `--no-subtyping` in the options would really have any effect. Closing this as pointless.
