### ISSUE TITLE
A list of modules to port

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#15]
Consider porting all of the following:

- [x] 2-Category.agda
- [x] 2-Category/Categories.agda
- [x] Adjunction.agda
- [x] Adjunction/Composition.agda
- [x] Adjunction/CompositionLaws.agda
- [x] Agda.agda
- [x] Agda/ISetoids/Cocomplete.agda
- [x] Agda/ISetoids/Cocomplete/Helpers.agda
- [x] Agda/ISetoids/Complete.agda
- [x] Arrow.agda
- [x] Bicategory.agda
- [x] Bicategory/Helpers.agda
- [x] Bigroupoid.agda
- [x] Categories.agda
- [x] Categories/Products.agda
- [x] CategorySolver.agda
- [x] Closed.agda
- [x] Cocone.agda
- [x] Cocones.agda
- [x] Coend.agda
- [x] Coequalizer.agda
- [x] Colimit.agda
- [x] Comma.agda
- [x] Comma/Functors.agda
- [x] Comonad/Cofree.agda
- [x] Congruence.agda
- [x] Coproduct.agda
- [x] DinaturalTransformation.agda
- [x] End.agda
- [x] Enriched.agda
- [x] Equalizer.agda
- [x] Equivalence/Strong.agda
- [x] Fam.agda
- [x] Fibration.agda
- [x] Free.agda
- [x] Functor/Algebras.agda
- [x] FunctorCategory.agda
- [x] Functor/Coalgebras.agda
- [x] Functor/Constant.agda
- [x] Functor/Diagonal.agda
- [x] Functor/Discrete.agda
- [x] Functor/Equivalence/Strong.agda
- [x] Functor/Monoidal.agda
- [x] Functor/Product.agda
- [x] Functor/Representable.agda
- [x] Globe.agda
- [x] GlobularSet.agda
- [x] Graphs.agda
- [x] Graphs/Underlying.agda
- [x] Grothendieck.agda
- [x] Groupoid/Coproduct.agda
- [x] Groupoid/Product.agda
- [x] Lift.agda
- [x] Limit.agda
- [x] Monad/Algebra.agda
- [x] Monad/Algebras.agda
- [x] Monad/Coproduct.agda
- [x] Monad/EilenbergMoore.agda
- [x] Monad/Kleisli.agda
- [x] Monad/Strong.agda
- [x] Monoidal.agda
- [x] Monoidal/Braided.agda
- [x] Monoidal/Braided/Helpers.agda
- [x] Monoidal/Cartesian.agda
- [x] Monoidal/CartesianClosed.agda
- [x] Monoidal/Cartesian/Pentagon.agda
- [x] Monoidal/Closed.agda
- [x] Monoidal/Helpers.agda
- [x] Monoidal/IntConstruction.agda
- [x] Monoidal/Symmetric.agda
- [x] Monoidal/Traced.agda
- [x] Morphism/Cartesian.agda
- [x] Morphism/Indexed.agda
- [x] NaturalIsomorphism.agda
- [x] NaturalTransformation.agda
- [x] Normalise.agda
- [x] Object/BinaryCoproducts.agda
- [x] Object/BinaryProducts/Abstract.agda
- [x] Object/BinaryProducts.agda
- [x] Object/BinaryProducts/N-ary.agda
- [x] Object/Coproduct.agda
- [x] Object/Coproducts.agda
- [x] Object/Exponential.agda
- [x] Object/Exponentiating/Adjunction.agda
- [x] Object/Exponentiating.agda
- [x] Object/Exponentiating/Functor.agda
- [x] Object/Indexed.agda
- [x] Object/IndexedProduct.agda
- [x] Object/IndexedProducts.agda
- [x] Object/Initial.agda
- [x] Object/Product.agda
- [x] Object/Product/Morphisms.agda
- [x] Object/Products.agda
- [x] Object/Products/N-ary.agda
- [x] Object/Products/Properties.agda
- [x] Object/SubobjectClassifier.agda
- [x] Object/Terminal.agda
- [x] Object/Terminal/Exponentials.agda
- [x] Object/Terminal/Exponentiating.agda
- [x] Object/Terminal/Products.agda
- [x] Object/Zero.agda
- [x] Opposite.agda
- [x] Power.agda
- [x] Power/Functorial.agda
- [x] Power/NaturalTransformation.agda
- [x] Preorder.agda
- [x] Presheaf.agda
- [x] Presheaves.agda
- [x] Product/Projections.agda
- [x] Product/Properties.agda
- [x] Profunctor.agda
- [x] Pushout.agda
- [x] RigCategory.agda
- [x] Square.agda
- [x] SubCategory.agda
- [x] Terminal.agda
- [x] Topos.agda
- [x] WithFamilies.agda
- [x] Bifunctor.agda
- [x] Category.agda
- [x] Comonad.agda
- [x] Cone.agda
- [x] Cones.agda
- [x] Discrete.agda
- [x] Functor.agda
- [x] Functor/Algebra.agda
- [x] Functor/Coalgebra.agda
- [x] Functor/Core.agda
- [x] Functor/Hom.agda
- [x] Functor/Properties.agda
- [x] Groupoid.agda
- [x] Lan.agda and Ran.agda
- [x] Monad.agda
- [x] Morphisms.agda
- [x] NaturalTransformation/Core.agda
- [x] Product.agda
- [x] Pullback.agda
- [x] Slice.agda
- [x] Yoneda.agda

**Comment by HuStmpHrrr** [comment]
@JacquesCarette are you able to check the boxes above?

**Comment by JacquesCarette** [comment]
Yes, I can (and just checked `Functor/Discrete.agda`). Unfortunately, this doesn't let me do anything 'alternate', like cross it off.  For example, `Equalizer.agda` was empty in the original library, so we should ignore it.  Same with Enriched and Closed.  And `Bifunctor/NaturalTransformation` was not useful enough to bother with.  Should these also be checked?

**Comment by HuStmpHrrr** [comment]
`Equalizer` is defined so we should check it. I don't know why some modules are empty in the original library. there are some of those I would like to define. if you think there are some modules that are not too useful we can check them off and regard them as done.

**Comment by JacquesCarette** [comment]
Dropping Object/Indexed, IndexedProduct and IndexedProducts.

**Comment by JacquesCarette** [comment]
Object/Exponentiating (and supporting functions) are not used anywhere, and not really documented on nLab either, so dropping for now. Unless there's a specific request later.

**Comment by JacquesCarette** [comment]
Presheaves -> Category.Construction.Presheaves.

**Comment by HuStmpHrrr** [comment]
> Object/Exponentiating (and supporting functions) are not used anywhere, and not really documented on nLab either, so dropping for now. Unless there's a specific request later.

I believe that's a special status of exponential. 

https://ncatlab.org/nlab/show/exponential+object#related_notions

> More generally, a morphism f:Y→A is exponentiable (or powerful) when it is exponentiable in the over category C/A.
> ...
> Conversely, if X is such that X^Y exists for all Y, we say that X is exponentiating. 

but I am not sure if this concept is useful outside the context of CCC.

**Comment by JacquesCarette** [comment]
If there's anything you feel we do need, go ahead and 'uncheck' it.

**Comment by HuStmpHrrr** [comment]
no I don't find it useful. i was just quote the related part from nLab. in CCC exponential is a bifunctor so this concept indeed looks less important to me.

**Comment by HuStmpHrrr** [comment]
`Terminal.agda` becomes `Categories.instance.One`.

**Comment by JacquesCarette** [comment]
`2-Categories/Categories` (which was far from finished) becomes `Categories.2-Category.Instance.Cats` (and is done).

**Comment by HuStmpHrrr** [comment]
`Object/SubobjectClassifier.agda` moved to `Diagram.SubobjectClassifier`.

**Comment by JacquesCarette** [comment]
`Categories.Products` is `Categories.Category.Monoidal.Instance.Cats`

**Comment by JacquesCarette** [comment]
`Congruence` really doesn't seem useful (or stylistically compatible), so I'm going to drop it.

**Comment by JacquesCarette** [comment]
`Functor.Coalgebras` (which should be `Category.Construction.F-Coalgebras`) was empty, so is trivially "ported".  It still needs implemented, but that should be a different issue.

**Comment by JacquesCarette** [comment]
Skipping `Lift`, as I'm hoping it is largely not needed. [Not quite true, but I think it's overkill]

**Comment by JacquesCarette** [comment]
`Monad.Algebra` and `Monad.Algebras` were empty.

**Comment by JacquesCarette** [comment]
`Normalize` is very cool - but should be done via Reflection these days rather than in this manner. Drop.

**Comment by JacquesCarette** [comment]
Looks to me like the contents of `Object/BinaryProducts/Abstract` has already been put elsewhere?

**Comment by JacquesCarette** [comment]
`Topos` was empty - marking it as done. It can be done later.

**Comment by JacquesCarette** [comment]
`Object/Terminal/Exponentiating` not useful enough, dropping.  Other two `Object/Terminal/...` are in `Categories.Object.Product.Construction` as they are constructors of products (and exponentials) [under some assumptions, in this case, of there being a Terminal object around). This file may get extended with more constructions.

**Comment by JacquesCarette** [comment]
`Monoidal/IntConstruction` was highly unfinished, and is quite non-trivial. So while it should eventually be implemented, that's not an issue of 'porting'.

**Comment by JacquesCarette** [comment]
`Monad/Coproduct` isn't really a coproduct of monads. It is rather a construction of (trivial) monad(s) when an underlying category has all coproducts. This doesn't seem all that useful, dropping.

**Comment by JacquesCarette** [comment]
I'm marking `2-Category` as done, as there is now an adequate definition. `2-Category/Categories` was unfinished. The only way to hope to do it would be to port the old `2-Category` as it was done (unbundled, by hand), so that the axioms can hard-code which equality to use. A horrible hack, but it would allow things to work a bit more. Really not worth it, IMHO, as `Bicategory` is really the better option.

**Comment by JacquesCarette** [comment]
`CategorySolver` is another piece of technology that doesn't seem worth porting at all.

**Comment by JacquesCarette** [comment]
@HuStmpHrrr : all that's left is `Adjunction/CompositionLaws`, but I've looked at it, and I don't strongly feel like porting it. In particular, it looks to me like a proper port would require using `Mates`, and you're the expert there.  We could even decide to do that one 'in the future', open an issue and close this one.

**Comment by HuStmpHrrr** [comment]
all these composition laws require equivalence of adjoints. is it reasonable to talk about equivalence between adjoints? we had it before but it was removed. I supposed not. then we just don't need this module.

**Comment by JacquesCarette** [comment]
In a proof-relevant setting based on Hom-Setoids, it doesn't make sense to ask for too-strong an equivalence of Adjoints (thus the mention of `Mates`). So we can't just port this, it would be a whole new implementation.  Which can be done later, when someone actually needs it.
