### ISSUE TITLE
add reflexivity proofs to ensure duality conversions are indeed definitional

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#157]
the idea is the ensure `refl` proves all duality conversions.

c.f. #87 #89

**Comment by JDemler** [comment]
I am not 100% sure I understand the task correctly.
Would it be for example this for the `Iso⇒op-Iso` conversion in `Categories.Morphism.Duality`:

```agda
Iso⇒op-Iso-Refl : ∀(iso : Iso f g) → op-Iso⇒Iso (Iso⇒op-Iso iso) ≡ iso
Iso⇒op-Iso-Refl iso = refl
```

And then similar proofs for all duality conversions, so functions in `Duality`-Modules that do not emit `Set`s?

**Comment by JacquesCarette** [comment]
Yes - but also that for all `C : Category`, `op (op C) ≡ C` is also proved by `refl`. We want to make sure that all dualities, even the really simple ones, hold definitionally.  [This didn't use to be the case, and there are still some that do not hold.]

**Comment by HuStmpHrrr** [comment]
here is a good example:

https://github.com/agda/agda-categories/blob/6ce0b7ba5c7246dc978c7c6f8e2bf6045a4619e7/src/Categories/Category/Finite/Fin.agda#L163-L166

an extra note I would make is that these proofs should be private, because it shouldn't be used anywhere.

**Comment by JacquesCarette** [comment]
I was kind of thinking of gathering all such proofs in one location (not sure of the name, but perhaps involving `Duality` and `Properties`?) instead.  Then these trivial theorems wouldn't be imported by anyone else - but also wouldn't cost typechecking (and loading) time of the 'main' library, unlike the above.  They can surprisingly add up! [I've been on a speeding things up kick, it's hard and subtle, and all sorts of details make a non-trivial difference]

**Comment by HuStmpHrrr** [comment]
I think they should be at the bottom of the same file as the definition. it's a quick check and not meant to be used anyways.

**Comment by JacquesCarette** [comment]
I'm mostly mentioning because what I used to believe was 'quick' has been reshaped quite a bit by the last few days' worth of profiling. I'm not against putting it in the same file, at least until it becomes an efficiency problem.  [I wonder if `private` definitions that aren't used end up in the `.agdai`? ]

**Comment by sstucki** [comment]
Why not put these in separate (toplevel) modules/files? E.g. for structures defined in module `X`, add a separate `X.Duality` or `X.Helpers` module. That allows for separate imports, less clutter, less typechecking overhead.

**Comment by JDemler** [comment]
Alright. For now I'll put these proofs in extra modules inside `Duality.aga` modules to keep the imports clean and make the proofs themselves private.

Example for `Categories.Category.Duality`:

```agda
module DualityConversionProperties where

  open import Relation.Binary.PropositionalEquality using (_≡_; refl)

  private
    opOpRefl : Category.op C.op ≡ C
    opOpRefl = refl

```
Is that ok?

How should I name these proofs?

**Comment by JacquesCarette** [comment]
First this particular one, I would be tempted to call is `op-involutive`.

**Comment by HuStmpHrrr** [comment]
I would move the import to the top of the file, but that's just stylistic remark.

you can prepare a PR so that we can have something more concrete to discuss.

**Comment by JDemler** [comment]
I opened the PR.
Tomorrow I will add more proofs so we have more to discuss :)

**Comment by HuStmpHrrr** [comment]
I think we can close this issue since I addressed all of the rest
