### ISSUE TITLE
coherence condition for braided monoidal category

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#16]
compatibility with unitors.

c.f. https://ncatlab.org/nlab/show/braided+monoidal+category

**Comment by JacquesCarette** [comment]
There's  nice hint of how to do that at https://math.stackexchange.com/questions/912510/coherence-in-braided-monoidal-categories.  The [original paper](http://maths.mq.edu.au/~street/JS1.pdf) is supremely unhelpful in that respect.

**Comment by JacquesCarette** [comment]
I think this is actually done -- @sstucki ?

**Comment by sstucki** [comment]
> I think this is actually done -- @sstucki ?

Yes. See #67 and #77.
