### ISSUE TITLE
Add IsTerminal/IsInitial predicates

### ISSUE THREAD

**Issue by TOTBWF** [agda/agda-categories#171]
When dealing with limits, it is often useful to be able to say that some specific, constructed (co)cone is the (co)limiting (co)cone. For examples, see https://ncatlab.org/nlab/show/preserved+limit. However, without a way of saying that a given object is the terminal/initial object in a category, this becomes difficult to express. I propose that we add predicates for all of these cases.

**Comment by JacquesCarette** [comment]
Agreed - PR for that would be most welcome!

**Comment by TOTBWF** [comment]
Working on a PR right now, would you all prefer to have the predicates seperated a la:
```agda
record Terminal : Set (o ⊔ ℓ ⊔ e) where
  field
    ⊤ : Obj
    ! : {A : Obj} → (A ⇒ ⊤)
    !-unique : ∀ {A} → (f : A ⇒ ⊤) → ! ≈ f

  !-unique₂ : ∀ {A} {f g : A ⇒ ⊤} → f ≈ g
  !-unique₂ {A} {f} {g} = begin
    f ≈˘⟨ !-unique f ⟩
    ! ≈⟨ !-unique g ⟩
    g ∎
    where open HomReasoning

  ⊤-id : (f : ⊤ ⇒ ⊤) → f ≈ id
  ⊤-id _ = !-unique₂

record IsTerminal (⊤ : Obj) : Set (o ⊔ ℓ ⊔ e) where
  field
    ! : {A : Obj} → (A ⇒ ⊤)
    !-unique : ∀ {A} → (f : A ⇒ ⊤) → ! ≈ f
```
Or bundled together into the definition of `Terminal`:
```agda
record IsTerminal (⊤ : Obj) : Set (o ⊔ ℓ ⊔ e) where
  field
    ! : {A : Obj} → (A ⇒ ⊤)
    !-unique : ∀ {A} → (f : A ⇒ ⊤) → ! ≈ f

  !-unique₂ : ∀ {A} {f g : A ⇒ ⊤} → f ≈ g
  !-unique₂ {A} {f} {g} = begin
    f ≈˘⟨ !-unique f ⟩
    ! ≈⟨ !-unique g ⟩
    g ∎
    where open HomReasoning

  ⊤-id : (f : ⊤ ⇒ ⊤) → f ≈ id
  ⊤-id _ = !-unique₂

record Terminal : Set (o ⊔ ℓ ⊔ e) where
  field
    ⊤ : Obj
    is-terminal : IsTerminal ⊤

  open IsTerminal is-terminal public
```

**Comment by JacquesCarette** [comment]
`Groupoid` was done using option 2, so to be consistent, we should go with that.

Until this library reaches 1.0, I'm fine with a non-trivial amount of breaking changes.

**Comment by HuStmpHrrr** [comment]
touching the definitions of both `Terminal` and `Initial` would be too much. I think it suffices to define `is-terminal : IsTerminal ⊤` in `Terminal`, so most of the code can stay as is.

**Comment by JacquesCarette** [comment]
What do you mean by 'too much'? It's tedious, but it's not so bad. Or are we already at the stage where we really don't want to break compatibility?

**Comment by HuStmpHrrr** [comment]
I am thinking that's a lot of changes. but if that's acceptable I am fine with that.

**Comment by HuStmpHrrr** [comment]
close due to #184
