### ISSUE TITLE
tag for Agda 2.6.1 compatible version

### ISSUE THREAD

**Issue by alexarice** [agda/agda-categories#173]
Is it possible to add a tag to a commit that is known to typecheck with Agda 2.6.1? This will allow us to package a non-broken version on nixpkgs without just picking a random commit

**Comment by JacquesCarette** [comment]
`v0.1.2` is that tag (that I have also released). It is, as far as I can tell, the least-upper-bound of commits that are compatible.

**Comment by alexarice** [comment]
That's great, thanks

**Comment by alexarice** [comment]
I've just tried this out, unfortunately this commit doesn't build as it uses deprecated modules from the standard library. In particular it uses `Data.List.Any` which was fixed in this commit https://github.com/agda/agda-categories/commit/cb45c256753301b90f98318427a161a1122a058e#diff-c1a3a9626bd9de859ba7591145be9f29

**Comment by JacquesCarette** [comment]
Ok, thanks, I'll make another release.

**Comment by JacquesCarette** [comment]
`v0.1.3.1` hopefully will work.  I did do a fresh install on a new machine and ran the tests, and they worked.

**Comment by alexarice** [comment]
I'll give it a try, sorry for all the hassle

**Comment by alexarice** [comment]
Seems to work, thanks for all the help 👍

**Comment by JacquesCarette** [comment]
No problem, I'm super happy to have dedicated users (it's been a while... I kind of missed being a maintainer, actually).
