### ISSUE TITLE
Category instances for agda stdlib things

### ISSUE THREAD

**Issue by glittershark** [agda/agda-categories#176]
Back in the day, mostly as an excuse to teach myself both agda and category theory, I did a [bunch of formalizations of categorical properties for various built-in agda things](https://github.com/glittershark/categories) on top of copumpkin/categories. I was just revisiting some of that work, because I missed relaxing at the end of a long day with a proof checker, and discovered this library - which I'm super glad exists! My question for the maintainers - I'm gonna go start working through porting over some of those proofs into this library, for no reason other than that it's fun - is this something you'd want contributed back here? And if so, where would it belong? Any other things you'd want to tell an emphatic non-mathematician before I go too deep down the rabbit hole?

**Comment by JacquesCarette** [comment]
It's really hard to respond at that high level of generality.

We do welcome PRs, very much. We vastly prefer small PRs over large ones, even if that means dozens of PRs. That way we can make sure every piece gets a proper look, and is integrated with the rest.

I'm also quite happy to reply to design questions here on Issues. So before going down a big rabbit hole, ask.

If you're thinking of contributing a lot of 'instances', we should definitely discuss that. I think it makes a huge amount of sense to have a large library of instances - but the ones in this library should be the ones that tend to be re-used internally. I have myself been thinking of starting a category-instances for all those things which build on top of this library but doesn't naturally fit into it.

There are bits of documentation here and there. It could be improved a lot - PRs for that are super-welcome. But specific complaints are too. That's easier to fix than generic "not enough docs".

**Comment by glittershark** [comment]
hey, thanks for the really quick, pointed, and detailed reply! all good stuff to know. I'm totally on board with a `category-instances` library and think it makes a lot of sense - eg I'm currently going down the path of proving the list functor (and then maybe, and then the product bifunctor probably) - more than happy to redirect that to another repo if you go off and start it
