### ISSUE TITLE
Better naming for `Square`

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#18]
extending https://github.com/agda/agda-categories/issues/5#issuecomment-508801244

`Square` is more than squares. potentially `Morphism.Reasoning` a better place for it?

**Comment by JacquesCarette** [comment]
Agreed.

**Comment by HuStmpHrrr** [comment]
https://github.com/agda/agda-categories/commit/7c22ad40804e9895f30a33279c06505df1f2774f resolved this.
