### ISSUE TITLE
adjoint functor theorem

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#180]
I think it's a good idea to add adjoint functor theorem using the solution set predicate

**Comment by HuStmpHrrr** [comment]
this, however, will break #172 even further.

**Comment by HuStmpHrrr** [comment]
I am stuck. I don't think the way I am looking into it is correct. I should check how other libraries do this.

**Comment by JacquesCarette** [comment]
When I did a quick Google on the topic, I found nothing. Maybe ask on the CS Theory stackexchange?  I can also ask on the CT zulip chat, if you'd like.

Also, some details of where you got stuck might help.  Check in the code with holes in a branch?

**Comment by HuStmpHrrr** [comment]
I think I was dumb. It's probably working. let me think about it for a bit more while.

**Comment by HuStmpHrrr** [comment]
OK this is finally done.

**Comment by JacquesCarette** [comment]
Hurray!  That seemed quite difficult - what were the big sticking points? What are the items learned from this, that should perhaps be recorded?

**Comment by HuStmpHrrr** [comment]
it shouldn't have taken this long if i worked on it fulltime. the point is that the definition of continuous functor was wrong. it wasn't strong enough. this is dealt with in #184 . another thing is that we also need to prove a separate solution set property for initial object.

**Comment by JacquesCarette** [comment]
"the definition of continuous functor was wrong" is definitely a big deal. Was that inherited from the old library?

**Comment by HuStmpHrrr** [comment]
no, it's not. it's just messed up. i shouldn't call it wrong, it's just missing coherence condition. the right one gots in already in #184. essentially the previous definition only requires the apexes to be isomorphic, but the right definition should be cone preservation, which turns out to be the definition given by @TOTBWF . I have fixed the theorems mentioning it and proved some more in #187

**Comment by sstucki** [comment]
Sorry to be late to the party, but shouldn't the two definitions of (co)limit preservation be equivalent? Doesn't an iso on the apex (of a limit) induce a cone-iso via the universal property of the limit? Basically, the UIP induces a unique morphism between the corresponding cones, which has to be equal to the iso (by uniqueness), no?
