### ISSUE TITLE
is the definition of product preserving functor correct?

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#194]
https://github.com/agda/agda-categories/blob/master/src/Categories/Functor/Cartesian.agda

I find it's not quite the same as what I would expect. for example, 
https://github.com/agda/agda-categories/blob/dfa6dd47a23992e6b9108e09e42d0bf5d881d719/src/Categories/Functor/Cartesian.agda#L26
this doesn't look right to me as this morphism alone is not enough to show `Functor.F₀ F CA.⊤` to be a terminal object. consider a category with global elements, then in this category, this morphism just exists. this is not sufficient to prove this object is also a terminal object. the right definition should ensure that `Functor.F₀ F CA.⊤` is a terminal object.

the same goes the products, a natural transformation doesn't look enough to me.

**Comment by JacquesCarette** [comment]
You are correct. What should have been implemented is defined properly at https://ncatlab.org/nlab/show/monoidal+functor.

**Comment by HuStmpHrrr** [comment]
does that make a product-preserving functor though? we do have the weak version implemented: https://github.com/agda/agda-categories/blob/master/src/Categories/Functor/Monoidal.agda

**Comment by sstucki** [comment]
> does that make a product-preserving functor though?

I think it does. The "strong" version means `ε` and `⊗-homo` are (natural) isos, and since both the terminal object and products are define up to unique iso, the functor does indeed map products to products.

I wouldn't be surprised if the coherence conditions are provable from the universal properties too but I haven't checked.

**Comment by HuStmpHrrr** [comment]
that is true. c.f. for example theorem 5.6 and 5.7 in https://arxiv.org/pdf/1602.04860.pdf

I am though giving a more direct definition and define strong monoidal functor separately. wip in https://github.com/HuStmpHrrr/agda-categories/tree/feature/cartesian
