### ISSUE TITLE
More automation (Travis), including sanity checking

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#20]
As per comments on c968c74, we need to set up a Travis instance with sanity checks to enforce the agreed upon conventions.

**Comment by gallais** [comment]
I got a [basic build](https://github.com/gallais/agda-categories/pull/1) running to generate HTML docs just like for the stdlib,
unfortunately the library requires too much memory for the machines travis has.

Trying to build against `master` now to see whether compact regions will help.
Worried about #91

**Comment by JacquesCarette** [comment]
Thanks a lot for working on this, the help is most appreciated.
