### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#208]
Given that PR #207 has just been merged, the current version will be incompatible with 1.3, so we need to make a release asap.

**Comment by HuStmpHrrr** [comment]
ah! I just made a release, 0.14. we could make a 0.14.1 for minor stuff.

**Comment by HuStmpHrrr** [comment]
https://github.com/agda/agda-categories/releases/tag/v0.14

**Comment by turion** [comment]
@HuStmpHrrr did you intend 0.1.4 instead of 0.14?

**Comment by HuStmpHrrr** [comment]
yuk, I did. does that break anything? I can do a `0.1.4.1` release if that's better.

**Comment by gallais** [comment]
You can [edit the release](https://github.com/agda/agda-categories/releases/edit/v0.14) to fix the issue.

**Comment by HuStmpHrrr** [comment]
ok I did. so I will close this issue

**Comment by turion** [comment]
> does that break anything?

Not a great deal I believe, but nixpkgs and https://github.com/agda/package-index might get confused ;)
