### ISSUE TITLE
Inference and subcategories

### ISSUE THREAD

**Issue by conal** [agda/agda-categories#217]
I’ve been encountering inference difficulties when using `Categories.Category.SubCategory`. Below is a simplified example:

``` agda
open import Level
open import Algebra.Bundles

open import Categories.Category.Core using (Category)
open import Categories.Category.Instance.Setoids using (Setoids)
open import Categories.Category.SubCategory (Setoids 0ℓ 0ℓ)

open Category (FullSubCategory Magma.setoid)

_ : ∀ {A} → A ⇒ A
_ = id
```

The error message (referring to the use of `id` in the last line):

``` agda
__∙__16 : Algebra.Core.Op₂ (Magma.Carrier A)  [ at /Users/conal/Agda/cat-linear/src/T7.agda:11,5-7 ]
_∙-cong_19
  : Algebra.Definitions.Congruent₂ (λ z z₁ → (A Magma.≈ z) z₁)
    __∙__16  [ at /Users/conal/Agda/cat-linear/src/T7.agda:11,5-7 ]
```

If I replace `Magma` by a structure with more operations, such as `Ring`, I see more such errors, failing to infer each operation and associated property.

I’d appreciate any insights about causes and cures for this error.

**Comment by JacquesCarette** [comment]
And it was answered on the mailing list. For those who stumble upon this later: the implicits really can't be inferred here, so need to be given explicitly.
