### ISSUE TITLE
Structrues to Bundles?

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#244]
Does it sound better to rename `*.Structures` to `*.Bundles`, following stdlib https://github.com/agda/agda-stdlib/blob/master/src/Relation/Binary/Bundles.agda?

**Comment by JacquesCarette** [comment]
We currently have 2 `.Structure` (note the lack of 's'). I'm fine with calling them `Bundles` (or `Bundle` since they seem to be singular in our use?)
