### ISSUE TITLE
Proof that a Cartesian category is monoidal ?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#255]
I tried to find it in the library, and couldn't. Did I miss it? It would be nice to add a post to [this MO question](https://mathoverflow.net/questions/382239/proof-that-a-cartesian-category-is-monoidal) competing with Lean!

**Comment by sstucki** [comment]
https://github.com/agda/agda-categories/blob/d07746023503cc8f49670e309a6170dc4b404b95/src/Categories/Category/Cartesian.agda#L267

**Comment by sstucki** [comment]
Or more specifically:
https://github.com/agda/agda-categories/blob/d07746023503cc8f49670e309a6170dc4b404b95/src/Categories/Category/Cartesian.agda#L334

**Comment by JacquesCarette** [comment]
Perfect, thank you.  Hmm, that file is huge, might want to split it up...
