### ISSUE TITLE
`Category.Product` belongs to `Category.Construction`?

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#27]
similarly, `Discrete`, `Slice` and `SubCategory`?

**Comment by JacquesCarette** [comment]
Strictly speaking, yes. But somehow I'm seeing differences, and wanting to place certain things under `Construction` while others not. Some "constructions" seem to be very important in category theory (such as all the ones listed here) and can belong directly under `Category`.

I do realize that my argument is vague and subjective. But I don't want super-long names for things that are likely to be used a lot.

We could also just put them all under `Construction`.

**Comment by HuStmpHrrr** [comment]
it's fine. I don't want to put them into `Construction` either. I just want to make sure there is a reason why.
