### ISSUE TITLE
move to github-actions

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#284]
We've run out of tokens on the free CI. We need to move to github-actions. I can do the actual work, but I'd appreciate getting some pointers (was it @gallais who did it for agda-stdlib?)

For example is [this](https://doisinkidney.com/posts/2020-11-18-agda-github-action.html) a good set of instructions?

**Comment by gallais** [comment]
Started an experiment here: https://github.com/gallais/agda-categories/pull/2

**Comment by JacquesCarette** [comment]
NB: I removed the .travis.yml, as it is no longer used.
