### ISSUE TITLE
Release that's compatible to stdlib 1.7?

### ISSUE THREAD

**Issue by ice1000** [agda/agda-categories#287]
Is there going to be this thing

**Comment by gallais** [comment]
A good first step would be to open a PR changing the CI variable to use 2.6.2 and 1.7
and see whether it builds: https://github.com/agda/agda-categories/blob/master/.github/workflows/ci-ubuntu.yml#L47

**Comment by JacquesCarette** [comment]
It's going to be a thing, yes. I would be happy to see PRs. My Agda time is mostly being spent on finishing material for a paper, but I can definitely do timely reviews.

**Comment by Akshobhya1234** [comment]
I have created a PR #288 as first step. 
The build is failing with error: Empty `where' block (ignored) in .../NaturalTransformation/NaturalIsomorphism/Monoidal/Braided.agda
Error: Process completed with exit code 42.

I need help on how to resolve the issue.

**Comment by gallais** [comment]
Have you tried removing the empty `where` block?

**Comment by Akshobhya1234** [comment]
> Have you tried removing the empty `where` block?

@gallais Thanks! The build is now successful. Do I need to update in README.md?

**Comment by turion** [comment]
> Do I need to update in README.md?

Yes I think this makes sense in general.

**Comment by turion** [comment]
Is there going to be a git tag and a release? This would be great, because otherwise it might be broken on `nixpkgs`: https://github.com/NixOS/nixpkgs/pull/130424#issuecomment-885563001

**Comment by turion** [comment]
> Yes I think this makes sense in general.

See https://github.com/agda/agda-categories/pull/293

**Comment by JacquesCarette** [comment]
Shoot, I cut the release before I merged that in... I guess I'll do another. Sigh.

**Comment by JacquesCarette** [comment]
Done.
