### ISSUE TITLE
Not able to show two hom functors are naturally isomorphic

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#29]
the problem lies in that the two functors map to setoids category in different universe level.

this is kind of bad, because it means going from the naturally isomorphic hom functors to unit-counit definition also would not work.

I suppose the workaround is to implement `Lift` functor: https://github.com/copumpkin/categories/blob/master/Categories/Lift.agda

**Comment by JacquesCarette** [comment]
Can you give me more details? When I've encountered such things before, sometimes it was because things were not as polymorphic as they should have been (like an early version of `Enriched` had 3 level parameters whereas it naturally should have 4; in fact, it might be even more complex than that, where one might want Level functions to be fully general).

`Lift` is still a possibility, of course, but I'd rather explore a little bit more before resorting to that.

**Comment by HuStmpHrrr** [comment]
this following natural isomorphism cannot be defined:

```agda
NI : NaturalIsomorphism Hom[L-,-] Hom[-,R-]
```

actually I think about it and realize that Lift won't work.

I think the problem is lack of cumulative universe in Agda. the core issue is that C and D have different universe level so their hom setoids are also in two different levels, which make them live in two different `Setoids`.

**Comment by JacquesCarette** [comment]
But `Function.Inverse.Inverse` has no problem with that. So why does `NaturalIsomorphism` not work? I'm guessing there something along the way that is less universe polymorphic than it could be.

**Comment by HuStmpHrrr** [comment]
because `Inverse` works for two any setoids, while `NaturalIsomorphism` requires the functors to have the same domain and codomain category.

**Comment by JacquesCarette** [comment]
I get the impression that this a case where traditional CT cheats. It feels like some 'adjustment' functors are needed to make things on both sides match up.  Kind of like the `Monad` laws had to be patched to not rely on associativity being true 'on the nose'. The domain and codomain categories have got to be equivalent [else this is all heterogeneous nonsense], but this has to be shown/added to the normal statement?

**Comment by HuStmpHrrr** [comment]
or probably not cheated because in the traditional CT category of all sets does exist, but it is not the case in Agda.

I suppose there needs to be an injection functor which maps smaller Setoids to larger one.

**Comment by JacquesCarette** [comment]
If you could push everything that works, and put those that don't in comments, when I have time, I'll experiment.  And yes, an injection functor might just do the trick!

**Comment by HuStmpHrrr** [comment]
nothing is working because Agda doesn't even allow me to state that type. I will begin with the injection functor and see if it solves the problem.

**Comment by HuStmpHrrr** [comment]
alright! I am done: https://github.com/agda/agda-categories/commit/df39bef44194016605b7d5bcda6286e70583c8f3
