### ISSUE TITLE
`Instance.X.Properties` instead of many `Instance`

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#32]
I am tempted to show `Cats` has all exponentials, which makes `Cats` a cartesian closed category. the problem is that the proof of cartesian closed category is in `Monoidal`, and where should cartesian closed category lives. I figure that probably `Category.Instance.Cats.Properties` is a better place to fit all these properties and is a single place to find the properties of `Cats`. `Sets`, `Setoids` have a similar situation.

**Comment by JacquesCarette** [comment]
Give in to the temptation :smiley: .  I agree with the proposal to create `.Properties` for this purpose, and moving previous code to that location.

**Comment by HuStmpHrrr** [comment]
it turns out the universe level are inconsistent. I will leave it for now.

**Comment by JacquesCarette** [comment]
The universe levels of what exactly are inconsistent?  Up to now, I've found that all non-trivial level issues were quite informative [like the problem of Homs in Adjoint, which has now convinced me that the unit-counit definition is the right one, and the Hom-set one is a special case that only works when size issues are ignored.]

**Comment by HuStmpHrrr** [comment]
the problem is that `Cats` is incapable of internalizing the `Functors` category of categories in it, because `Functors` lifts universe levels to much bigger one, so I guess in Agda it is not possible to show `Cats` is a CCC.

**Comment by JacquesCarette** [comment]
https://ncatlab.org/nlab/show/Cat does warn of size issues.

And I just checked -- `Functors` does not have a `suc` in it. It does however basically insist that all levels in both input categories be equal.  So for `Category o o o`, that should be able to internalize `Functors`.

**Comment by HuStmpHrrr** [comment]
that is true indeed. it is a very special case though.

**Comment by JacquesCarette** [comment]
It might be the only case provable in Agda. In some ways, it might also be the only 'true' case... Those size issues are real. Agda Levels are a very good proxy for them.

**Comment by JacquesCarette** [comment]
It feels like there are two issues here -- one about Cats being a CCC, and the other where to put certain properties.  Both should be looked at, but shouldn't be linked.  What should *this* issue be about?

**Comment by HuStmpHrrr** [comment]
this issue should be about the latter. I think in general it's a good idea to place properties close to where a concept is defined.

**Comment by JacquesCarette** [comment]
This issue seems obsolete, in the sense that the library now does have quite a few `.Properties` files. And I've trained myself to look there, and it works.  I will articulate a 'design' of that, and put it somewhere.
