### ISSUE TITLE
Bicategory terminology

### ISSUE THREAD

**Issue by maxsnew** [agda/agda-categories#338]
Categories.Bicategory.agda defines the following as "horizontal composition"
```agda
  -- horizontal composition
  _∘ₕ_ : {A B C : Obj} → B ⇒₁ C → A ⇒₁ B → A ⇒₁ C
  _∘ₕ_ = _⊚₀_
```
This terminology is a bit strange to me. This is the composition of the 1-cells, whereas I've always heard "horizontal composition" to refer to the "parallel" composition of 2-cells, as [here](https://ncatlab.org/nlab/show/horizontal+composition), which is in the library of course:
```agda
  _⊚₁_ : {A B C : Obj} {f h : B ⇒₁ C} {g i : A ⇒₁ B} → f ⇒₂ h → g ⇒₂ i → f ⊚₀ g ⇒₂ h ⊚₀ i
  α ⊚₁ β = Functor.F₁ ⊚ (α , β)
```

I think the traditional terminology makes sense because vertical/horizontal are both constructions on 2-cells. I suggest we rename `_∘ₕ_` to be an alias for `_⊚₁_`, and maybe we can give `_∘₁_` as the alias for 1-cell composition instead.

**Comment by JacquesCarette** [comment]
`git blame` points to @HuStmpHrrr . I'm surprised that @sstucki didn't mention anything, since he's played around with Bicategory more than anyone else.

**Comment by HuStmpHrrr** [comment]
yes, this is awkward. I agree with this change.

**Comment by maxsnew** [comment]
Ok so this is a somewhat big breaking change are we agreed on it before I do it?
