### ISSUE TITLE
Decide when to do a release

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#39]
I think the library is close to being in a state to be officially released. I think #23 should be fixed first, just so that it works with a currently-released library.  What other issues should be closed before a release?

I might wish to call the release 0.1.  There's still lots to do, but it is quite usable as is.

**Comment by HuStmpHrrr** [comment]
I suppose you mean the library should go after stdlib 1.2, right? do you know when is that? it seems to take a while. many issue are low hanging fruit so there should be plenty of time for those to be closed.

**Comment by gallais** [comment]
The CHANGELOG for the stdlib is currently fairly small. We usually release
whenever a lot of new content has landed (~1k lines of CHANGELOG for the
past few versions) rather than on a fixed schedule.

AFAIU you only have a constraint because of `levelOfTerm / levelOfType`
so it may be worth redefining these locally for this release if you want
to do so fairly soon.

**Comment by JacquesCarette** [comment]
I meant to release now-ish. And then try to bring in some of the library into stdlib 1.2, piece by piece.  And indeed we should go back to having a local definition for `levelOfTerm / levelOfType` for that initial release.

We can do a 0.2 release when a bunch more issues are closed.  I think what's there now is worth releasing.

**Comment by HuStmpHrrr** [comment]
alright, that makes sense.

**Comment by HuStmpHrrr** [comment]
I believe there are other spots where it requires the latest release, e.g. I recall that there are some refactors of `Function` which affects this library.

**Comment by JacquesCarette** [comment]
It would be good to pinpoint that.  And if it is in a 'remote enough' corner of the library, we might be able to pull that out?

**Comment by HuStmpHrrr** [comment]
I will try out what's missing. we don't have to modify the main branch. we can fork a release branch and make the specialization over there. I will first deal with #43 then this one.

**Comment by HuStmpHrrr** [comment]
https://github.com/agda/agda-categories/tree/release/v0.1 depends only on stdlib v1.1. what else do we need to do a release?

**Comment by JacquesCarette** [comment]
I was originally going to say 'nothing', but it seems that at least issue #44 should be fixed. I've looked at the rest of the issues, and it seems to me that's the only show-stopper.

**Comment by JacquesCarette** [comment]
Now that #44 is fixed, I think we can release. With a proper warning that it's a 0.1 and many things may still change.

**Comment by HuStmpHrrr** [comment]
yeah, the branch is ready. I will just merge whatever in the master branch to the release branch and make sure everything compiles.

**Comment by HuStmpHrrr** [comment]
a release is done and the library compiles with stdlib v1.1: https://github.com/agda/agda-categories/releases/tag/v0.1

**Comment by JacquesCarette** [comment]
Thanks!  I was going to make an explicit announcement on the mailing list - anything specific you would like me to mention?

**Comment by HuStmpHrrr** [comment]
nothing particular that I can come up with.
