### ISSUE TITLE
NaturalNumber -> NNO?

### ISSUE THREAD

**Issue by sergey-goncharov** [agda/agda-categories#391]
In `agda-categories/src/Categories/Object/NaturalNumber.agda`, I suggest renaming `NaturalNumber` to `NNO` (and adapt related names accordingly). It is not one number, it is really number**s**, and then more accurately (and standard) would be `NaturalNumberObject`. But then, `NNO` would be better, it is also a standard abbreviation. I would rename the file to `NaturalNumbers.agda`, as a more suggestive name. Agreed?

**Comment by JacquesCarette** [comment]
Agreed.
