### ISSUE TITLE
ensure names reflect the kinds of properties

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#4]
I noticed that there are names in some definitions that are not quite reasonable.

For example, https://github.com/agda/agda-categories/blob/master/Categories/Object/Product/Core.agda
```agda
    commute₁  : π₁ ∘ ⟨ h , i ⟩ ≈ h
    commute₂  : π₂ ∘ ⟨ h , i ⟩ ≈ i
    universal : π₁ ∘ h ≈ i → π₂ ∘ h ≈ j → ⟨ i , j ⟩ ≈ h
```

here `universal` shouldn't be `universal`, but `unique`, because it reflects the uniqueness of product. rather, `commute`s are universality.

probably the names should be reviewed to achieve consistency.

**Comment by JacquesCarette** [comment]
I completely agree that `universal` seems to be mis-named. And certainly `commute₁` is not very indicative of the actual property of the first/second projection.

**Comment by HuStmpHrrr** [comment]
`universal` is renamed to `unique` in https://github.com/agda/agda-categories/commit/68ea72ea3bec356b50bc8bc569a8ecc7be15bd11

**Comment by JacquesCarette** [comment]
I renamed `commute` to `project` (and to `inject` for `Coproduct`). I think we agree about this, and should enshrine this in our naming conventions. Thus this issue can be closed.
