### ISSUE TITLE
Support stdlib 2.0

### ISSUE THREAD

**Issue by turion** [agda/agda-categories#405]
[Agda stdlib 2.0 has recently been released](https://github.com/agda/agda-stdlib/blob/v2.0/CHANGELOG.md), but [unfortunately agda-categories doesn't compile with it](https://github.com/NixOS/nixpkgs/pull/273765/checks?check_run_id=19562607525). Maybe this can be fixed easily?

**Comment by Taneb** [comment]
See also https://github.com/agda/agda-categories/pull/352.

I think we might be blocked by https://github.com/agda/agda-stdlib/issues/2228 for updating `Setoids`.

**Comment by turion** [comment]
> I think we might be blocked by https://github.com/agda/agda-stdlib/issues/2228 for updating Setoids.

Ah, that would mean that there would be no agda-categories release for agda-stdlib 2.0?

**Comment by JacquesCarette** [comment]
There will definitely be a release of agda-categories for 2.0. We might have to create a few now-missing functions to do it, but it will happen!

**Comment by JacquesCarette** [comment]
@turion : it's coming - #406 now typechecks. It still needs cleaned up, but I don't expect that will take too long.
