### ISSUE TITLE
Which is the 'true' Zero category?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#49]
Consider the following:
```agda
  Zero′ : Category o ℓ e
  Zero′ = record
    { Obj = Lift o ⊥
    ; _⇒_ = λ _ _ → Lift ℓ ⊤
    ; _≈_ = λ _ _ → Lift e ⊤
    ; id = lift tt
    ; _∘_ = λ _ _ → lift tt
    }

  Zero′-⊥ : Initial
  Zero′-⊥ = record
    { ⊥ = Zero′
    ; ! = record
      { F₀ = λ { (lift x) → ⊥-elim x }
      ; F₁ = λ { {A = lift () } }
      ; identity = λ { {A = lift () } }
      ; homomorphism = λ { {()} }
      ; F-resp-≈ = λ { {()} }
      }
    ; !-unique = λ f → record
      { F⇒G = record { η = λ {()} ; commute = λ { {()} } }
      ; F⇐G = record { η = λ {()} ; commute = λ { {()} } }
      ; iso = λ ()
      }
    }
```
which shows that Agda is just as happy with this definition of 'the' initial object of Cats. This feels vaguely suspicious. What am I missing?

**Comment by JacquesCarette** [comment]
Update: I can complete the proof that `Zero` and `Zero′` are strongly equivalent. So I guess nothing is amiss after all. Nevertheless, I continue to not quite understand what's going on.

**Comment by HuStmpHrrr** [comment]
initial objects are unique only up to isomorphism, so strongly equivalent should be an evidence of that.

**Comment by JacquesCarette** [comment]
Categorically-speaking, I understand that. I guess the question I'm asking is much more of a CS question, since the difference seems to rely on call-by-value (i.e. forcing some of the `⊥` types to reveal themselves as uninhabited).
It's still a little odd to me that, once `Obj` is empty, you get a 'choice' of what to stick in for `Hom` and that choice does not actually matter.

**Comment by gallais** [comment]
> It's still a little odd to me that, once Obj is empty, you get a 'choice' of what to stick in for Hom and that choice does not actually matter.

I think @ppedrot may have something to say about this.

**Comment by JacquesCarette** [comment]
Since there is no code to fix related to this issue, I'll close it, even though I feel that there is still a question to be answered.
