### ISSUE TITLE
Library design discussion

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#5]
This is an issue for discussion about how the library should be design, from various aspects, including module structure and naming conventions. The overall principle should be to stay close with style guideline in standard library.

## Module structure

I propose that the libary should contain the following top level modules:

1. `Object`, which contains definitions of objects, e.g. initial and terminal objects, products, and exponentials.
2. `Morphism`, which contains definitions of morphisms, e.g. epis and monos.
3. `Diagram`, which contains definitions of diagram in a category, e.g. pullbacks and limits.
4. `Category`, which contains definitions of various categories, e.g. monoidal category, bi-category and ccc.
5. `Functor`, which contains definitions of various functors, e.g. hom functors, profunctors.
6. `NaturalTransformation`, which contains definitions of natural transformations, e.g. natural isomorphisms.
7. `Adjoint`, which contains definitions of adjoint functors, e.g. proadjoint.

I suppose there will be needs for other top level modules, e.g. `Algebra`, `Coalgebra`. We can add more once there is a need.

## Naming

Naming conventions should comply with standard library. For example, module names are usually singular, with the exception of the top level module `Categories` and `Properties`.

For variables, I propose following conventions.

1. `A, B, C, D, X, Y, Z` are for objects.
2. `f, g, h, i, a, b, c` for morphisms.
2. `C, D, E` are for categories. Clearly, the conventions for objects and categories collide. Sometimes it is not a problem, but when it does, I propose to use calligraphic letters `𝒞, 𝒟, ℰ`, for categories. They can be input in emacs by \McC, \McD, \McE.
3. `F, G, H, I` for functors.
4. `α, β, γ, η` for natural transformations. 

When defining structures, I propose the names should match the idea of UMP. e.g. if it's a universality property, then it should be called `universal`; if it is a uniqueness property, then it should be called `unique`.

## Other style problem.

1. Use generalized variables whenever possible. 
2. Avoid unnecessary parentheses.

**Comment by JacquesCarette** [comment]
After doing part of #1 and getting used to the library, I agree with the above design for the naming conventions.  [Though see some of the issues I added recently.]

A lot of the things under `Square` right now really are not about 'commutative squares' (which is kind of what I expected from the name), but really various things about 'morphism reasoning'. I therefore suggest that all of these be moved to be under `Morphism.Reasoning`.

Lastly, I think we need to find a better home for "Examples of categories" than under `Category` (and some of them are scattered about too). It could be `Category.Examples`, though I'm not that happy with that suggestion. Nor with top-level `Examples`. I kind of like `Category.Of` as a kind of pun (category of sets, category of categories, etc).

**Comment by HuStmpHrrr** [comment]
I think it makes sense to name `Morphism.Reasoning` instead.

for the special categories, I think `Category.Instance(s)` looks better.

my next step is to deal with CCC and related concepts, but I am busy with a deadline this few days so I will join you once I get over it.

**Comment by JacquesCarette** [comment]
We have a (small) window of opportunity to improve the naming, we should grab it!

No worries about the timing - I happened to have a window now. Next week, I'm at a conference in Europe, so it's unclear where my time will be spent.

**Comment by JacquesCarette** [comment]
One more thing: I would like to minimize the use of `rewrite`. I prefer explicit proofs, and some of the proofs using `rewrite` seem too magical.

**Comment by HuStmpHrrr** [comment]
there isn't really an opportunity for `rewrite` in the raw category theoretic part in this library. the part I did in `Isomorphism` is kind of a meta-argument to formalize a general argument people usually make informally.

**Comment by JacquesCarette** [comment]
As an issue, I think everything here is agreed to. I'll link to this issue on the wiki, to remember it, but there's no point in keeping it open.
