### ISSUE TITLE
`id-comm` is odd

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#50]
`id-comm` is defined in `Categories.Category.Core` as a definitional extension to a `Category` record.

Is that really where it belongs? It seems really out of place.  Feels like it ought to be in `Categories.Morphism`, for example.

Also, almost all uses are actually of the 'other' version, so the code has a lot of `Equiv.sym id-comm` (in various guises) strewn around. That is quite ugly, so I think that ought to have its own name. But I reluctant to add it to the `Category` record.

**Comment by HuStmpHrrr** [comment]
it is odd indeed. `id-unique` is also similar.

**Comment by JacquesCarette** [comment]
`id-unique` is fixed.  Working on pulling out `id-comm` into `Categories.Morphism.Reasoning` (and add `id-comm-sym`). Tedious but smooth.

**Comment by JacquesCarette** [comment]
That commit indeed fixes this.
