### ISSUE TITLE
Missing dependency `Relation.Binary.Construct.Closure.ReflexiveTransitive.Equivalence`?

### ISSUE THREAD

**Issue by sstucki** [agda/agda-categories#54]
Compiling Everything fails with the error

    Categories/Category/Construction/Graphs.agda:29,8-86
    Failed to find source of module
    Relation.Binary.Construct.Closure.ReflexiveTransitive.Equivalence

I'm using the latest version (`master`) of the standard library. Am I missing a patch?

**Comment by JacquesCarette** [comment]
No, that's my bug. I was experimenting with `WeakGraph` as the proper notion of underlying graph (I've abandoned that for now, may get back to it later) and this was part of the experiment. It's not needed, I'll fix it asap.

**Comment by JacquesCarette** [comment]
Fixed by d8dc5081833
