### ISSUE TITLE
Cats is CartesianClosed (when all levels the same)

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#61]
I tried to prove this, got a fair ways in, and got stuck.  I don't think it is fundamental, just that I'm missing something that will likely turn out to be simple.  Also, my definitions might be off a bit, which certainly wouldn't help matters. 
I've pushed my attempts onto branch 'CatsCCC' (as I can't attach .agda files easily here). Holes 3 and 5 in particular.  I think the rest are ok, just tedious.

**Comment by JacquesCarette** [comment]
So I think I know what the source of difficulty is: the definition of 'exponential object' used assumes that some products (as necessary) exist; but we already know all products exist. The problem is that the definition doesn't use the product just given.  But of course the it is CCC is with respect to that one product.  [This definition is inherited from the original port].  I think that if the definition was adjusted so that the exponential object was coherent, by construction, with the given product, lots of things would be considerably simpler.  And it would match the definitions in the literature too.

**Comment by HuStmpHrrr** [comment]
actually the current behavior is correct.

consider a trivial example. usually we say a product of `A` and `B` is `A × B`. However, it doesn't have to be the *canonical* representation of the product. for example, `B × A` is also an legitimate representation. in fact, there isn't a preference between both; they are just equally good, and there are other equally good representations. the uniqueness part of products concludes all such best representations are isomorphic and that's good enough. that the exponential part does not make assumption of concrete representation of a product is consistent with this extensional view.

**Comment by JacquesCarette** [comment]
The current behaviour is definitely not wrong. I agree with your reasoning.

I wonder if anyone has ever proved it in full generality though?  I really have no idea of how to proceed in those 2 holes. I suspect that existing proofs are either just sketches or 'for convenience' pick one product, since they are all "the same" anyways.

**Comment by HuStmpHrrr** [comment]
I did it in https://github.com/agda/agda-categories/commit/1c7e2f44bb31e7f502b26d256e81cdc8f62ad5e3

it is not too difficult. the problem is that there are slow computation parts. the idea is to make use of the UMP of the products in the construction. assuming a canonical construction is morally correct, because if we only inspect objects and morphisms extensionally consistently, there shouldn't be a problem. this is seen in many other constructions where properties like associativity etc are ignored.

**Comment by JacquesCarette** [comment]
Thanks.  A couple of hours after I posted my comment, your remarks finally sunk in properly, and it finally occurred to me to use the UMP of products.  Still, there was quite a bit of work to do to make it all come together!  Very nice.

**Comment by sstucki** [comment]
I developed @HuStmpHrrr's insight a bit further in #90.
