### ISSUE TITLE
Increase the precedence of _⟩∘⟨refl over refl⟩∘⟨_

### ISSUE THREAD

**Issue by MirceaS** [agda/agda-categories#62]
https://github.com/agda/agda-categories/blob/2eb7858ec634a2fe44767528014b4ac21f5ef061/Categories/Category/Core.agda#L64

I believe `_⟩∘⟨refl` should have a different precedence than `_⟩∘⟨_` and `refl⟩∘⟨_` as I had some issues with agda struggling to parse expressions like `⟨ refl⟩∘⟨ something ⟩∘⟨refl ⟩` and since we want right associativity, `_⟩∘⟨refl` should have the higher precedence so I would propose changing it to a 5. For me, doing this little change made the quoted expression work in the end.
What do you think?

**Comment by JacquesCarette** [comment]
That makes sense - I'll do that once I have a chunk of time to run the test suite.
