### ISSUE TITLE
Swap left and right congruence

### ISSUE THREAD

**Issue by rei1024** [agda/agda-categories#7]
https://github.com/agda/agda-categories/blob/ab86789b1561c224e75d97494677d01f510b002b/Categories/Object/BinaryProducts.agda#L82-L86

**Comment by JacquesCarette** [comment]
I'm willing to believe that they are incorrect - but can you provide evidence, maybe by pointing out a couple of things in the standard library with the other order?

**Comment by rei1024** [comment]
Here are the standard library's definitions.
https://github.com/agda/agda-stdlib/blob/442abf2b3418d4d488381a2f8ca4e99bbf8cfc8e/src/Algebra/FunctionProperties.agda#L117-L121
related issue: https://github.com/agda/agda-stdlib/issues/695

**Comment by JacquesCarette** [comment]
Perfect! Also it means that we might be able to use `LeftCongruent` and `RightCongruent` directly in the definitions. At least that would insure consistency.

**Comment by rei1024** [comment]
I agree with that. Anyway, thanks for replying!

**Comment by HuStmpHrrr** [comment]
i see so the previous library disagrees in naming conventions by quite a bit.

**Comment by JacquesCarette** [comment]
I think that, until recently, the standard library was self-inconsistent in this way too. So it shouldn't be surprising.
