### ISSUE TITLE
Modularize and clean up Categories.Category.Construction.Graphs

### ISSUE THREAD

**Issue by sstucki** [agda/agda-categories#75]
The module `Categories.Category.Construction.Graphs` should be refactored.

The module currently contains
    * basic definitions (graphs and their morphisms),
    * the definition of the category of graphs,
    * the functor mapping graphs to their free categories,
    * an adjunction between the forgetful functor and the free functor,
    * various helper/utility constructs and lemmas (e.g. path equality, etc.).

These should probably all go in separate modules. Some of the code should be moved to the standard library.

(See comments in the code for more details.)

**Comment by sstucki** [comment]
Note that there is currently a pending PR (#42) that involves changes to the module. Any further changes should probably be made _after_ that PR has been closed.

**Comment by JacquesCarette** [comment]
I entirely agree, that module is a mess.

**Comment by JacquesCarette** [comment]
Closed by PR #262 .
