### ISSUE TITLE
Implement Mac Lane comparison Functor?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#78]
See the Coq code at https://github.com/ekiciburak/ComparisonTheorem-MacLane .  There's a paper too.  Looks like fun.

**Comment by JacquesCarette** [comment]
@TOTBWF how much of this issue is dealt with by your PR #125  ?

**Comment by TOTBWF** [comment]
I implemented the Eilenberg-Moore version of this, which is pretty similar in character. Doing the Kleisli version ought to be pretty straightforward 🙂 I suspect that proving uniqueness will be easier as well, as you don't need to show that two T-modules/T-actions are equivalent, only objects and arrows.

I'll take a look into finishing this off in the next couple of days.

**Comment by Taneb** [comment]
Can this issue be closed now?

**Comment by TOTBWF** [comment]
Yeah, Should be good to go.

**Comment by JacquesCarette** [comment]
I haven't forgotten - I just want to double-check for myself that it's all done. Most likely is.

**Comment by JacquesCarette** [comment]
Sorry to be so slow - it's all great. And the proof is readable (and short), unlike the Coq one.
