### ISSUE TITLE
Monad

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#8]
Toying with come copy of the old code, I finally encountered one problem: the definition of Monad doesn't go through without irrelevance, as least in the way it was defined in the old library.  In particular, one gets the error
```
F₁ (Category.id C) != Category.id C of type
(C Category.⇒ F₀ (F₀ A)) (F₀ (F₀ A))
when checking that the expression μ ∘ʳ F has type
NaturalTransformation (F ∘F F ∘F F) (F ∘F F)
```
on the line
```agda
     assoc     : (μ ∘₁ (F ∘ˡ μ)) ≡T (μ ∘₁ (μ ∘ʳ F))
```
Those two are, of course, "equal", but not definitionally equal.

I am completely convinced that Heterogeneous equality is **not** the solution. A different definition of the associativity law is probably the way to go. One that does not require that definitional equality as an intermediate step.

**Comment by JacquesCarette** [comment]
@HuStmpHrrr if you have any insights on this, I'd appreciate it. [Monad at nLab](https://ncatlab.org/nlab/show/monad) unhelpfully admits that there's a problem with the usual definition, but explicitly omits the coherence isos anyways!  On Twitter, Bryce Clarke [made some suggestions](https://twitter.com/8ryceClarke/status/1139652528662933504) that I haven't had a chance to try yet.

**Comment by HuStmpHrrr** [comment]
sorry I don't know. I feel that it's because there is no good notion of equal functors. was it that heterogeneity or irrelevant helped in the previous library? it seems that the previous library relies on a heterogeneous equality to express equal functors.

**Comment by JacquesCarette** [comment]
Irrelevance helped in the previous library, because I think that `F₁ (Category.id C)` used to compute to `Category.id C` but now it doesn't anymore. At least, I think that's the issue.

**Comment by JacquesCarette** [comment]
Fixed! See commits 5d92eb and e15713.
