### ISSUE TITLE
Consider adding a symmetric version of `commute` in the definition of natural transformation

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#87]
since we are in the mood of considering `op` of `op` being definitionally equal to the original definition, in the case of natural transformation, we might also need something like this:

https://github.com/agda/agda-categories/blob/9a9c4abda552657e973c600692cc2d3ffaa37520/Categories/NaturalTransformation/Core.agda#L37

in the opposite of a natural transformation, the `commute` proof is constructed by `sym`ming `commute`. the consequence is that, the `op` of `op` of a natural transformation is not definitionally equal to itself. to fix this, we shall add `sym-commute` in the same spirit as `sym-assoc` in the definition of `Category`.

in general, the rule of thumb is that, if an opposite can be defined by a definition, then it is a good idea to introduce redundancy to the original definition, so that `op` of `op` is the same as the original term. this is a good material in the paper.

**Comment by HuStmpHrrr** [comment]
indeed, this library has implemented this trick:

https://github.com/HoTT/HoTT/blob/35d9de1f587117cafebf7d7b1851bb177f173783/theories/Categories/NaturalTransformation/Core.v#L47-L48

**Comment by JacquesCarette** [comment]
Makes sense.  It's amusing that this is all starting to look like my work (with Amr Sabry) on reversible computation, where we go to great pains to make all our languages syntactically reversible. I wasn't expecting the same thing to make sense here too!

**Comment by sstucki** [comment]
Since there are now a bunch of 'redundant' fields in many records, would it make sense to add 'smart constructors' for these records that fill in the defaults?

For example, for `Category` one could have a 'constructor' `category` that takes 8 arguments (for the non-redundant fields) and fills in the remaining two? Additionally, some of the arguments that Agda can infer from the others could be made implicit (e.g. `Obj`, or morphism equality).

WDYT?

**Comment by JacquesCarette** [comment]
I'm definitely in favour.

**Comment by HuStmpHrrr** [comment]
@sstucki 
there has been such constructors, e.g. https://github.com/agda/agda-categories/blob/2d0a0cc0975e94a864ece5811308953f84e7f981/Categories/Category/Core.agda#L153-L154 , https://github.com/agda/agda-categories/blob/2d0a0cc0975e94a864ece5811308953f84e7f981/Categories/NaturalTransformation/Core.agda#L55-L56

If certain fields can be inferred, you can remove that field after pressing `C-c C-r`.

**Comment by sstucki** [comment]
Oops, thanks @HuStmpHrrr, I had completely missed these. 😳

Yes, this is pretty much what I had in mind. And it's nice that one can use record syntax with these too.

The only thing I don't like are the names. `xyzHelper` seems a bit too generic. Maybe we can come up with a better naming convention? For example, for the record `Category` the auxiliary record could be named `PlainCategory` or `BaseCategory`? And the names of the 'wrappers' is probably even more important, as these will be more visible in actual code. We could even use a symbolic name to reduce the visual overhead. E.g. just `category`/`nt`/`naturalTransformation` or something generic, like `《_》`?

I'm just brainstorming here, I'd love to hear other suggestions.

**Comment by HuStmpHrrr** [comment]
yeah helper might not be the best name. we can definitely change them.
