### ISSUE TITLE
Test against agda HEAD?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#91]
I'm seeing a lot of issues coming up against current HEAD, which is slated to be released soon. I'm concerned that only some of the bugs will be found, and that this library will stop type-checking. Best bet to prevent that is to test against HEAD and report any/all bugs so found. [I'm sure they would then be fixed]

Unfortunately, I don't have the bandwidth to do that right now - anyone else?

**Comment by JacquesCarette** [comment]
This is being worked on - I've got 2.6.1 installed on a VM (though I need to reinstall), and it looks like @asr is also trying [thanks!]

**Comment by HuStmpHrrr** [comment]
I have some older version of agda working (but still newer than 2.6.0.1 thx to cubical), I can only see some warnings from stdlib though. I don't think the library will receive much shock modulo the part coming from stdlib.

**Comment by HuStmpHrrr** [comment]
btw you can run multiple versions on the same machine at the same time. the way I do it is I pick a `stack.yaml` file and do `stack install`, which will install the binaries to `~/.local/bin`. I just need to rename the binaries to `*-2.6.1` and I can choose different versions of agda from emacs. very handy.

**Comment by asr** [comment]
Using `cabal-install`, you can use `cabal install --program-suffix=-2.6.1`. I guess there is something similar in `stack`.

**Comment by JacquesCarette** [comment]
I'll try to set that up on my servers.  It does look like, modulo a couple of small fixes, it works.  Unfortunately, it also looks like the memory requirements have gone up. [I'm working on splitting up the worst offender; it's also kind of fun].

**Comment by sstucki** [comment]
This discussion reminds me that it would be nice to set up continuous integration for the library, e.g. using Travis.

Maybe we could adopt the Travis configuration from the standard library?

**Comment by JacquesCarette** [comment]
Yes, absolutely!  I just haven't had any spare cycles to do that.

**Comment by HuStmpHrrr** [comment]
I doubt Travis provides sufficient memory though. I remember it's 6g?

**Comment by sstucki** [comment]
Yea, that might be an issue. I wonder how the standard library gets around this.

Their config suggests they get by with under 4G:

```
  - export RTS_OPTIONS="+RTS -M3.5G -H3.5G -A128M -RTS"
```
(From https://github.com/agda/agda-stdlib/blob/master/.travis.yml)

Do they just have less memory-hungry code? There must be some rather complex bits in the stdlib, no?

**Comment by MatthewDaggitt** [comment]
> Do they just have less memory-hungry code? There must be some rather complex bits in the stdlib, no?

I think it's just that we split everything into relatively small parts, and we don't have any particularly large or complex proofs. (from my perspective, I'm glad as my laptop definitely isn't up to checking anything much larger!)

**Comment by JacquesCarette** [comment]
Some of the equational proofs in the library are monsters indeed.  I'm splitting some of them up into smaller pieces, hopefully that will help.  But I think we'll need ~6 Gigs. Luckily, I think current infrastructure can handle that.  If we need to go > 7Gigs, that's when things will start to be a real problem.

**Comment by JacquesCarette** [comment]
So CI has been done, and when this was set up, HEAD meant 2.6.1. Things work against that. Also, the memory requirements (because of fixes in 2.6.1) have gone down, so pretty much everything in here has been fixed.  It would be nice to be able to test against the latest and greatest, but that should be done in a new issue, later.
