### ISSUE TITLE
Error: Not in scope $

### ISSUE THREAD

**Issue by asr** [agda/agda-categories#92]
I'm getting the following error using Agda 2.6.0.1, standard library 1.2 and the [current](2d0a0cc0975e94a864ece5811308953f84e7f981) master:

```bash
$ agda Everything.agda
...
The module Function.Core doesn't export the following: _$_
when scope checking the declaration
  open import Function.Core using (_$_)
/some-path/Categories/Yoneda.agda:131,48-49
Not in scope:
  $ at /some-path/Categories/Yoneda.agda:131,48-49
when scope checking $
```

**Comment by MatthewDaggitt** [comment]
It should be Function.Base not Core. Looks like this must have been written
using the dev version of the standard library as Function.Core only
contained _$_ very briefly
