### ISSUE TITLE
Error: Ambiguous module name Function.Inverse

### ISSUE THREAD

**Issue by asr** [agda/agda-categories#93]
I'm getting the following error using Agda 2.6.0.1, standard library 1.2 and the [current](5a0a5e44824bd5729dfeecb6160285e0592f7791) master:

```bash
$ agda Everything.agda
...
/some-path/Categories/Yoneda.agda:14,13-29
Ambiguous module name Function.Inverse. It could refer to any one
of
  Function.Inverse
  Function.Bundles.Inverse (record module)
(hint: Use C-c C-w (in Emacs) if you want to know why)
when scope checking the declaration
  open import Function.Inverse using (Inverse)
```

**Comment by JacquesCarette** [comment]
The problem is that one can no longer import `Function` and `Function.Inverse` in the same file.  And the signature of those has changed too.   Fixing.
