### ISSUE TITLE
nice shorthand for Functor

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#99]
https://github.com/agda/agda-categories/blob/afe50323d35e8eaf664ba8c38e781dbd6f941cb6/Categories/Enriched/Functor.agda#L47-L48

this looks really nice. we should also have this for `Functor` as well.

**Comment by sstucki** [comment]
Yes, I think that would be good!

**Comment by sstucki** [comment]
Should I just implement this now, or should I wait until we have addressed #103?

**Comment by JacquesCarette** [comment]
#103 is thorny, and I want to think about it.  There are already users of this library, and this is going to break all of their code. I'm not against it, I just want to see if there's a way to provide an upgrade path that isn't too painful.

A long way to say that it would make sense to implement this now, but hopefully in a way that would be compatible with #103 also being implemented later.

**Comment by HuStmpHrrr** [comment]
let's move the discussion to #103, as it's more clear from the title.
